name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:

  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@v0.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
