name: snk

on:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:

  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate gif
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: dist
          author_name: 'snk[bot]'
          author_email: snk-bot@example.com
          message: Generate snk gif
