name: snk

on:
  schedule:
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:

  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Generate svg
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snk.svg?palette=github-dark
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: dist
          author_name: 'snk[bot]'
          author_email: snk-bot@example.com
          message: Generate snk svg
